<style>
body {
  display: flex;
  font-family: 'Courier New', Courier, monospace;
  justify-content: center;
  align-items: center;
}
</style>
<body>
  <span id="result">authorizing...</span>
</body>
<script>
  function saveAccessInfo(acc) {
    const tt = typeof acc === 'string' ? acc : JSON.stringify(acc)
    localStorage.setItem('gh-acc', btoa(tt))
  }
  async function main () {
    const query = new URLSearchParams(location.search)
    const $result = document.getElementById('result')
    if (query.get('error')) {
      $result.innerHTML = `<b>Error</b><br>${query.get('error')}<br>${query.get('error_description')}`
      return
    }
    const body = {
      appName: 'downGit',
      code: query.get('code'),
      state: localStorage.getItem('gh-salt')
    }
    try {
      // check gh-auth-worker.js for serverside implement
      const result = await fetch('/gh-auth', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(body)
      }).then(res => res.json())
      
      if (result && result.access_token) {
        saveAccessInfo(result)
        location.href = location.origin
        return
      }
      $result.innerHTML = `
      <b>Error</b> <br>
      failed to auth github ${result && result.error_description || ''}<br>
      please <a href="/">back to home</a> and auth again
      `
      console.warn('auth failed', result)
    } catch (e) {
      $result.innerHTML = `
      <b>Error</b> <br>
      failed to auth github, it's likely to be a network issue<br>
      please reload this page and try a gain
      `
      console.warn(e)
    }
  }
  main()
</script>